// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBUrojGSPSqP6sfJK3ZDtFgDNGdzJZF62k',
      appId: '1:735508976387:web:34ed5ef8fae3b60ca70f36',
      messagingSenderId: '735508976387',
      projectId: 'final-project-jp',
      authDomain: 'final-project-jp.firebaseapp.com',
      storageBucket: 'final-project-jp.appspot.com',
      measurementId: 'G-X31MN8HEK9',
      databaseURL: 'https://final-project-jp-default-rtdb.firebaseio.com/');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9WUQOZEqgoogoEguL-VCdVooeDSxMDc',
    appId: '1:735508976387:android:53106ef93e899f1da70f36',
    messagingSenderId: '735508976387',
    projectId: 'final-project-jp',
    storageBucket: 'final-project-jp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Q06mb-9ym2cvUcidMaEk_pftXOMX6c4',
    appId: '1:735508976387:ios:b71c631976a71ff2a70f36',
    messagingSenderId: '735508976387',
    projectId: 'final-project-jp',
    storageBucket: 'final-project-jp.appspot.com',
    iosClientId:
        '735508976387-lafpv4qbm7a7igo2iej1j29128t1928p.apps.googleusercontent.com',
    iosBundleId: 'com.example.squip',
  );
}
